app = "taskmaster-mcp"
primary_region = "mia"

[env]
LOG_LEVEL = "debug"
PORT = "8000"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8000
min_machines_running = 1
processes = [ "app" ]

[vm]
cpu_kind = "shared"
cpus = 1
memory = "256mb"

[build]
  dockerfile = "Dockerfile"  
